#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ "$OSTYPE" == darwin* ]]; then
  # setup nvm
  export NVM_DIR=~/.nvm
  source $(brew --prefix nvm)/nvm.sh
  # setup thefuck
  eval "$(thefuck --alias)"
fi

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir rbenv vcs)

fpath=("${ZDOTDIR:-$HOME}/.zcustom/functions" $fpath)
autoload -U ${ZDOTDIR:-$HOME}/.zcustom/functions/*(:t)

if [[ "$OSTYPE" == msys ]]; then
  alias scoop="powershell -noprofile -ex unrestricted scoop.ps1"
fi
