#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# TMUX
if which tmux >/dev/null 2>&1; then
    #if not inside a tmux session, and if no session is started, start a new session
    test -z "$TMUX" && (tmux attach || tmux new-session)
fi

if [[ "$OSTYPE" == darwin* ]]; then
  # setup nvm
  export NVM_DIR=~/.nvm
  source $(brew --prefix nvm)/nvm.sh
  # setup thefuck
  eval "$(thefuck --alias)"
fi

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir rbenv vcs)